# Generated by Django 4.1 on 2022-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.TextField(default=' ', max_length='255'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth',
            field=models.DateField(default='1910-01-01'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='johndoe@xpto.com', max_length=254),
        ),
    ]
