# Generated by Django 4.1 on 2022-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_adress_customer_birth_customer_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.TextField(default='', max_length='255'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
