# Generated by Django 4.1 on 2022-08-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_adress_customer_adress_complement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ddd',
            new_name='DDD',
        ),
    ]
