# Generated by Django 4.1 on 2022-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_ddd_customer_ddd'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(default='', max_length=5),
        ),
    ]
